linters:
  disable-all: true
  enable:
    - goconst
    - gofmt
    - revive
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - vet
    - vetshadow
    - errcheck
    - govet
    - typecheck
    - gocritic
    - unused

run:
  # timeout for analysis
  timeout: 5m

  skip-dirs:
    - hack

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/v3io/locator)
      - default
      - blank
      - dot

  revive:
    rules:
      # avoid  errorf: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)  messages
      - name: errorf
        disabled: true

  gocritic:
    disabled-checks:
      - commentFormatting # we dont want to enforce space before the comment text

issues:
  # List of regexps of issue texts to exclude
  exclude:
    - "comment on"
    - "error should be the last"

  exclude-rules:
    # list of excluded linters applied on test files
    - path: _test\.go
      linters:
        - goconst
