FROM golang:1.11 as builder
ADD ./ /go/src/github.com/v3io/locator
WORKDIR /go/src/github.com/v3io/locator
RUN make bin

FROM debian:stretch-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

COPY --from=builder /go/src/github.com/v3io/locator/cmd/locatorctl /usr/local/bin/locatorctl

CMD [ "locatorctl" ]
