# Copyright 2019 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Release

on:
  release:
    types:
      - created

  # Run Release on push to development for unstable
  push:
    branches:
      - development

env:
  RELEASE_REGISTRY: gcr.io
  RELEASE_REPO: iguazio
  ARTIFACTORY_REGISTRY: artifactory.iguazeng.com:6555

jobs:
  release:
    name: Release Docker Images
    runs-on: [ self-hosted, Linux ]
    steps:

      - name: Set unstable
        if: github.event_name == 'push'
        run: |
          echo "LABEL=unstable" >> $GITHUB_ENV

      - name: Set release
        if: github.event_name == 'release'
        run: |
          echo "LABEL=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Login to artifactory
        run: docker login -u ${{ secrets.ARTIFACTORY_DOCKER_USERNAME }} -p ${{ secrets.ARTIFACTORY_DOCKER_PASSWORD }} ${{ env.ARTIFACTORY_REGISTRY }}

      - name: Login to GCR
        run: |
          echo "$GCR_JSON_KEY" | docker login -u _json_key --password-stdin https://gcr.io
        env:
          GCR_JSON_KEY: ${{ secrets.GCR_IGUAZIO_JSON_KEY }}

      - name: Build image [GCR]
        run: make build
        env:
          REPOSITORY: ${{ env.RELEASE_REGISTRY }}/${{ env.RELEASE_REPO }}

      - name: Push image [GCR]
        run: make push
        env:
          REPOSITORY: ${{ env.RELEASE_REGISTRY }}/${{ env.RELEASE_REPO }}

      - name: Build image [Artifactory]
        run: make build
        env:
          REPOSITORY: ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.RELEASE_REPO }}

      - name: Push image [Artifactory]
        run: make push
        env:
          REPOSITORY: ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.RELEASE_REPO }}
